"""Added message_type field to chat history

Revision ID: 7b4767c005f4
Revises: a6ccd4722661
Create Date: 2026-05-04 23:06:09.341947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4767c005f4'
down_revision = 'a6ccd4722661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=16), nullable=False,server_default="global"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
